'use client';

import { Amplify } from 'aws-amplify';
import outputs from '../../amplify_outputs.json'; // This file is generated by 'npx ampx sandbox'

Amplify.configure(outputs, { ssr: true });

export default function ConfigureAmplifyClientSide() {
    return null;
}
