import PageWrapper from '@/components/wrappers/page-wrapper';
import outputs from '../../../amplify_outputs.json'; // This file is generated by 'npx ampx sandbox'
import { Amplify } from 'aws-amplify';
import ConfigureAmplifyClientSide from '@/components/providers/configure-amplify-client';

// Configures Amplify on the server side of the application
Amplify.configure(outputs, { ssr: true });

export default function ForgeLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <PageWrapper className="flex flex-col items-start justify-start relative md:pt-10 md:px-5">
            <ConfigureAmplifyClientSide />
            <div className="flex-1 flex flex-col w-full max-w-screen-2xl mx-auto">
                {children}
            </div>
        </PageWrapper>
    );
}
