#!/usr/bin/env ts-node

/**
 * Reads CloudFormation stack outputs and generates a .env.local file
 * for the frontend to consume.
 *
 * Usage:
 *   npx ts-node scripts/generate-frontend-env.ts test
 *   npx ts-node scripts/generate-frontend-env.ts prod
 */

import {
    CloudFormationClient,
    DescribeStacksCommand,
} from '@aws-sdk/client-cloudformation';
import * as fs from 'fs';
import * as path from 'path';

type Stage = 'test' | 'prod';

const STACK_PREFIX = 'skillforge';

// Map CDK output keys to frontend env var names
const OUTPUT_MAP: Record<string, string> = {
    ApiApiUrl: 'NEXT_PUBLIC_API_URL',
    AuthUserPoolId: 'NEXT_PUBLIC_USER_POOL_ID',
    AuthUserPoolClientId: 'NEXT_PUBLIC_USER_POOL_CLIENT_ID',
    AuthIdentityPoolId: 'NEXT_PUBLIC_IDENTITY_POOL_ID',
    StorageBucketName: 'NEXT_PUBLIC_S3_BUCKET',
};

async function getStackOutputs(
    stage: Stage
): Promise<Record<string, string>> {
    const client = new CloudFormationClient({
        region: process.env.AWS_REGION ?? 'eu-west-2',
    });

    const stackName = `${STACK_PREFIX}-${stage}`;

    const command = new DescribeStacksCommand({ StackName: stackName });
    const response = await client.send(command);

    const stack = response.Stacks?.[0];
    if (!stack) {
        throw new Error(`Stack "${stackName}" not found. Has it been deployed?`);
    }

    const outputs: Record<string, string> = {};
    for (const output of stack.Outputs ?? []) {
        if (output.OutputKey && output.OutputValue) {
            outputs[output.OutputKey] = output.OutputValue;
        }
    }

    return outputs;
}

function generateEnvContent(
    outputs: Record<string, string>,
    region: string
): string {
    const lines: string[] = [
        '# Auto-generated by infra/scripts/generate-frontend-env.ts',
        '# Do not edit manually — re-run the script after deploying.',
        '',
    ];

    for (const [outputKey, envVar] of Object.entries(OUTPUT_MAP)) {
        const value = outputs[outputKey];
        if (value) {
            lines.push(`${envVar}=${value}`);
        } else {
            console.warn(`⚠️  Output "${outputKey}" not found in stack outputs`);
        }
    }

    lines.push(`NEXT_PUBLIC_AWS_REGION=${region}`);
    lines.push('');

    return lines.join('\n');
}

async function main() {
    const stage = process.argv[2] as Stage;

    if (!stage || !['test', 'prod'].includes(stage)) {
        console.error('Usage: npx ts-node scripts/generate-frontend-env.ts <test|prod>');
        process.exit(1);
    }

    const region = process.env.AWS_REGION ?? 'eu-west-2';

    console.log(`📡 Fetching outputs from stack: ${STACK_PREFIX}-${stage}...`);

    const outputs = await getStackOutputs(stage);

    const envContent = generateEnvContent(outputs, region);

    // Determine output file
    const filename = stage === 'prod' ? '.env.production.local' : '.env.local';
    const outputPath = path.resolve(__dirname, '../../frontend', filename);

    fs.writeFileSync(outputPath, envContent, 'utf-8');

    console.log(`✅ Written to: ${outputPath}`);
    console.log('');
    console.log(envContent);
}

main().catch((err) => {
    console.error('❌ Error:', err.message);
    process.exit(1);
});
